import type { Company, Founder } from '@/types/company';

const founders: Founder[] = [
  { id: 'f1', name: 'Arjun Mehta', role: 'CEO & Co-founder', linkedin: 'https://linkedin.com', twitter: 'https://twitter.com' },
  { id: 'f2', name: 'Priya Sharma', role: 'CTO & Co-founder', linkedin: 'https://linkedin.com', twitter: 'https://twitter.com' },
  { id: 'f3', name: 'Wei Zhang', role: 'CEO & Founder', linkedin: 'https://linkedin.com', twitter: 'https://twitter.com' },
  { id: 'f4', name: 'Lucas Fernandez', role: 'CEO', linkedin: 'https://linkedin.com' },
  { id: 'f5', name: 'Anika Patel', role: 'CTO', linkedin: 'https://linkedin.com', twitter: 'https://twitter.com' },
  { id: 'f6', name: 'Omar Hassan', role: 'CEO & Co-founder', linkedin: 'https://linkedin.com' },
  { id: 'f7', name: 'Sophie Lefebvre', role: 'CTO & Co-founder', linkedin: 'https://linkedin.com', twitter: 'https://twitter.com' },
  { id: 'f8', name: 'Ravi Kumar', role: 'CEO', linkedin: 'https://linkedin.com', twitter: 'https://twitter.com' },
];

export const DUMMY_COMPANIES: Company[] = [
  {
    id: 'c1',
    name: 'Helios AI',
    tagline: 'Autonomous infrastructure for the next decade',
    description: 'Helios AI is building the infrastructure layer that enables autonomous agents to operate production systems safely. Our platform combines formal verification with real-time observability to give engineering teams confidence in deploying AI-driven automation at scale.',
    website: 'https://heliosai.com',
    stage: 'series-a',
    batch: 'YC W24',
    industry: 'Infrastructure',
    location: 'San Francisco, CA',
    remoteFriendly: true,
    techStack: ['Go', 'Rust', 'Kubernetes', 'PostgreSQL', 'gRPC'],
    openJobsCount: 5,
    founders: [founders[0], founders[1]],
    hiringDescription: 'We hire for long-term potential and love engineers who thrive in ambiguous, high-leverage environments. We move fast but write things down.',
    employeeCount: '25-50',
    foundedYear: 2022,
  },
  {
    id: 'c2',
    name: 'Archway',
    tagline: 'The developer platform for regulated industries',
    description: 'Archway makes it easy to build compliant software in healthcare, fintech, and legal. We abstract away the complexity of SOC 2, HIPAA, and GDPR compliance so engineering teams can ship features instead of filling out forms.',
    website: 'https://archway.dev',
    stage: 'seed',
    batch: 'YC S23',
    industry: 'Developer Tools',
    location: 'New York, NY',
    remoteFriendly: true,
    techStack: ['TypeScript', 'Node.js', 'React', 'PostgreSQL', 'AWS'],
    openJobsCount: 3,
    founders: [founders[2]],
    hiringDescription: 'Remote-first culture with in-person sprints. We value deep work and asynchronous communication.',
    employeeCount: '10-25',
    foundedYear: 2023,
  },
  {
    id: 'c3',
    name: 'Meridian Finance',
    tagline: 'Embedded financial rails for B2B SaaS',
    description: 'Meridian provides APIs for B2B SaaS companies to embed financial services — invoicing, collections, and credit — directly into their products. We handle the complex financial infrastructure so our customers can focus on their core product.',
    website: 'https://meridianfinance.io',
    stage: 'series-b',
    industry: 'Fintech',
    location: 'London, UK',
    remoteFriendly: false,
    techStack: ['Python', 'Django', 'React', 'PostgreSQL', 'Celery', 'Redis'],
    openJobsCount: 8,
    founders: [founders[3], founders[4]],
    hiringDescription: 'We are a London-first team that believes in in-person collaboration. Occasional remote ok for senior hires.',
    employeeCount: '50-100',
    foundedYear: 2021,
  },
  {
    id: 'c4',
    name: 'Novara',
    tagline: 'Real-time data pipelines, without the overhead',
    description: 'Novara is a managed streaming data platform that helps engineering teams build real-time applications without managing Kafka clusters. We provide Kafka-compatible APIs with a fully serverless backend that scales to billions of events per day.',
    website: 'https://novara.io',
    stage: 'seed',
    batch: 'YC W23',
    industry: 'Data Infrastructure',
    location: 'Remote',
    remoteFriendly: true,
    techStack: ['Rust', 'Go', 'Kafka', 'ClickHouse', 'TypeScript'],
    openJobsCount: 4,
    founders: [founders[5], founders[6]],
    hiringDescription: 'Fully distributed team across 10 time zones. We trust our people to do great work autonomously.',
    employeeCount: '15-30',
    foundedYear: 2023,
  },
  {
    id: 'c5',
    name: 'Pulse Health',
    tagline: 'Clinical intelligence at the point of care',
    description: 'Pulse Health is bringing AI-driven clinical decision support to frontline healthcare workers. Our platform integrates with existing EHR systems to surface evidence-based recommendations at the moment they matter most.',
    website: 'https://pulsehealth.ai',
    stage: 'series-a',
    industry: 'HealthTech',
    location: 'Boston, MA',
    remoteFriendly: true,
    techStack: ['Python', 'FastAPI', 'React', 'PostgreSQL', 'ML/AI', 'HL7 FHIR'],
    openJobsCount: 6,
    founders: [founders[7]],
    hiringDescription: 'Mission-driven team. We look for people who want to work on hard problems that genuinely improve lives.',
    employeeCount: '40-80',
    foundedYear: 2022,
  },
  {
    id: 'c6',
    name: 'Stratos',
    tagline: 'Cloud cost intelligence for platform teams',
    description: 'Stratos helps platform and FinOps teams understand, forecast, and optimize their cloud spending. We connect to your AWS, GCP, and Azure accounts to surface actionable cost insights without requiring any code changes.',
    website: 'https://stratos.cloud',
    stage: 'pre-seed',
    batch: 'YC S24',
    industry: 'Cloud Infrastructure',
    location: 'Seattle, WA',
    remoteFriendly: true,
    techStack: ['Go', 'Python', 'React', 'BigQuery', 'Terraform'],
    openJobsCount: 2,
    founders: [founders[0], founders[2]],
    hiringDescription: 'Early stage, high impact. Every hire shapes our culture and technical direction.',
    employeeCount: '5-15',
    foundedYear: 2024,
  },
  {
    id: 'c7',
    name: 'Sylva',
    tagline: 'Open-source observability that scales with you',
    description: 'Sylva is building the next generation of open-source observability tooling — logs, traces, and metrics in a single platform. We are committed to vendor-neutral standards and giving engineers full control over their data.',
    website: 'https://sylva.dev',
    stage: 'seed',
    industry: 'Developer Tools',
    location: 'Remote',
    remoteFriendly: true,
    techStack: ['Go', 'TypeScript', 'ClickHouse', 'OpenTelemetry', 'React'],
    openJobsCount: 7,
    founders: [founders[1], founders[3]],
    hiringDescription: 'Open-source first. We build in public and believe the best ideas come from the community.',
    employeeCount: '20-40',
    foundedYear: 2023,
  },
  {
    id: 'c8',
    name: 'Forge Labs',
    tagline: 'AI-native code review for engineering teams',
    description: 'Forge Labs makes AI code review that actually understands your codebase context. We integrate with GitHub and GitLab to provide meaningful, actionable feedback on every pull request — not just style nits.',
    website: 'https://forgelabs.dev',
    stage: 'series-a',
    batch: 'YC W22',
    industry: 'Developer Tools',
    location: 'San Francisco, CA',
    remoteFriendly: true,
    techStack: ['Python', 'TypeScript', 'React', 'PostgreSQL', 'LLMs'],
    openJobsCount: 9,
    founders: [founders[4], founders[5]],
    hiringDescription: 'We care deeply about craft. We expect engineers to own their work end to end.',
    employeeCount: '30-60',
    foundedYear: 2022,
  },
];
