import type { Job } from '@/types/job';

export const DUMMY_JOBS: Job[] = [
  {
    id: 'j1',
    title: 'Senior Backend Engineer',
    companyId: 'c1',
    companyName: 'Helios AI',
    location: 'San Francisco, CA',
    locationType: 'hybrid',
    type: 'full-time',
    salaryMin: 160000,
    salaryMax: 220000,
    salaryCurrency: 'USD',
    techStack: ['Go', 'Rust', 'Kubernetes', 'PostgreSQL', 'gRPC'],
    description: 'We are looking for a Senior Backend Engineer to join our infrastructure team and help build the core systems that power autonomous AI agents operating production systems. You will work across our runtime, control plane, and observability stack.',
    requirements: [
      '5+ years of backend engineering experience',
      'Strong proficiency in Go or Rust',
      'Experience with distributed systems and cloud-native infrastructure',
      'Familiarity with Kubernetes and container orchestration',
      'Experience with PostgreSQL or similar relational databases',
    ],
    responsibilities: [
      'Design and build scalable backend services for our agent runtime',
      'Collaborate with the infrastructure team on Kubernetes operator development',
      'Contribute to our open-source observability tooling',
      'Define and uphold engineering standards for reliability and performance',
      'Mentor junior engineers and participate in architecture reviews',
    ],
    postedAt: '2024-06-01',
    batch: 'YC W24',
    stage: 'series-a',
    industry: 'Infrastructure',
    matchPercentage: 91,
  },
  {
    id: 'j2',
    title: 'Full Stack Engineer',
    companyId: 'c1',
    companyName: 'Helios AI',
    location: 'San Francisco, CA',
    locationType: 'hybrid',
    type: 'full-time',
    salaryMin: 140000,
    salaryMax: 190000,
    salaryCurrency: 'USD',
    techStack: ['TypeScript', 'React', 'Next.js', 'Go', 'PostgreSQL'],
    description: 'Join our product team as a Full Stack Engineer and build the interfaces that give engineering teams visibility and control over their AI-driven automation. You will work closely with design and product to ship features that delight our users.',
    requirements: [
      '3+ years of full stack experience',
      'Strong TypeScript and React skills',
      'Experience with Next.js App Router',
      'Backend experience with Go or Node.js',
      'Keen eye for product quality and UX',
    ],
    responsibilities: [
      'Build and maintain our web application and dashboard',
      'Work with the backend team to design and consume internal APIs',
      'Ship high-quality, accessible UI components',
      'Collaborate closely with design and product management',
      'Write thorough tests and maintain engineering documentation',
    ],
    postedAt: '2024-05-28',
    batch: 'YC W24',
    stage: 'series-a',
    industry: 'Infrastructure',
    matchPercentage: 85,
  },
  {
    id: 'j3',
    title: 'Platform Engineer',
    companyId: 'c2',
    companyName: 'Archway',
    location: 'New York, NY',
    locationType: 'remote',
    type: 'full-time',
    salaryMin: 150000,
    salaryMax: 200000,
    salaryCurrency: 'USD',
    techStack: ['TypeScript', 'Node.js', 'AWS', 'Terraform', 'PostgreSQL'],
    description: 'Archway is looking for a Platform Engineer to help build the infrastructure that powers compliance automation for regulated industries. You will work on our multi-tenant cloud platform, developer APIs, and internal tooling.',
    requirements: [
      '4+ years of platform or infrastructure engineering experience',
      'Proficiency in AWS services (ECS, RDS, Lambda, SQS)',
      'Experience with Infrastructure as Code (Terraform preferred)',
      'Strong Node.js or Go skills',
      'Experience with multi-tenant SaaS architecture',
    ],
    responsibilities: [
      'Design and operate our multi-tenant AWS infrastructure',
      'Build internal developer platforms and tooling',
      'Drive security and compliance posture improvements',
      'Manage and improve CI/CD pipelines',
      'Respond to and resolve production incidents',
    ],
    postedAt: '2024-06-03',
    batch: 'YC S23',
    stage: 'seed',
    industry: 'Developer Tools',
    matchPercentage: 78,
  },
  {
    id: 'j4',
    title: 'Senior Frontend Engineer',
    companyId: 'c2',
    companyName: 'Archway',
    location: 'New York, NY',
    locationType: 'remote',
    type: 'full-time',
    salaryMin: 130000,
    salaryMax: 175000,
    salaryCurrency: 'USD',
    techStack: ['TypeScript', 'React', 'Next.js', 'TailwindCSS', 'Storybook'],
    description: 'We are looking for a Senior Frontend Engineer who cares deeply about developer experience and product quality. You will build our developer portal, documentation site, and internal dashboard.',
    requirements: [
      '4+ years of frontend engineering experience',
      'Expert-level TypeScript and React',
      'Experience building design systems',
      'Strong CSS skills (Tailwind preferred)',
      'Accessibility (a11y) experience is a strong plus',
    ],
    responsibilities: [
      'Build and evolve our developer portal and documentation site',
      'Create and maintain a shared component library',
      'Work with product and design on our core dashboard experience',
      'Advocate for frontend best practices and performance',
      'Mentor other engineers on frontend craft',
    ],
    postedAt: '2024-05-30',
    batch: 'YC S23',
    stage: 'seed',
    industry: 'Developer Tools',
    matchPercentage: 88,
  },
  {
    id: 'j5',
    title: 'Backend Engineer — Payments',
    companyId: 'c3',
    companyName: 'Meridian Finance',
    location: 'London, UK',
    locationType: 'onsite',
    type: 'full-time',
    salaryMin: 90000,
    salaryMax: 130000,
    salaryCurrency: 'GBP',
    techStack: ['Python', 'Django', 'PostgreSQL', 'Celery', 'Redis', 'Stripe'],
    description: 'Meridian is building the embedded financial rails that power B2B SaaS. We are looking for a Backend Engineer with payments experience to help build and scale our core payments and credit infrastructure.',
    requirements: [
      '4+ years of backend experience',
      'Strong Python skills with Django or FastAPI',
      'Experience with payment systems or financial APIs',
      'PostgreSQL and asynchronous task queues (Celery/Redis)',
      'Understanding of financial compliance requirements',
    ],
    responsibilities: [
      'Build and maintain our payments and credit APIs',
      'Integrate with payment processors and banking partners',
      'Design data models for financial ledger systems',
      'Ensure reliability, correctness, and auditability of financial data',
      'Collaborate with the fintech compliance team',
    ],
    postedAt: '2024-06-05',
    stage: 'series-b',
    industry: 'Fintech',
    matchPercentage: 72,
  },
  {
    id: 'j6',
    title: 'Distributed Systems Engineer',
    companyId: 'c4',
    companyName: 'Novara',
    location: 'Remote',
    locationType: 'remote',
    type: 'full-time',
    salaryMin: 170000,
    salaryMax: 230000,
    salaryCurrency: 'USD',
    techStack: ['Rust', 'Go', 'Kafka', 'ClickHouse', 'Kubernetes'],
    description: 'Novara is building the serverless streaming data platform of the future. We need a Distributed Systems Engineer who loves hard problems — consensus, replication, partitioning — and wants to build a platform used by thousands of engineers.',
    requirements: [
      '5+ years of distributed systems experience',
      'Deep understanding of streaming and messaging systems (Kafka, Pulsar)',
      'Strong Rust or Go skills',
      'Experience with ClickHouse or similar column-oriented databases',
      'Strong understanding of consensus protocols (Raft, Paxos)',
    ],
    responsibilities: [
      'Design and build core components of our streaming platform',
      'Implement and optimize our proprietary replication layer',
      'Work on performance tuning and capacity planning',
      'Write technical design documents and collaborate across the team',
      'Drive reliability and operational excellence',
    ],
    postedAt: '2024-06-02',
    batch: 'YC W23',
    stage: 'seed',
    industry: 'Data Infrastructure',
    matchPercentage: 95,
  },
  {
    id: 'j7',
    title: 'ML Engineer',
    companyId: 'c5',
    companyName: 'Pulse Health',
    location: 'Boston, MA',
    locationType: 'hybrid',
    type: 'full-time',
    salaryMin: 155000,
    salaryMax: 210000,
    salaryCurrency: 'USD',
    techStack: ['Python', 'PyTorch', 'FastAPI', 'PostgreSQL', 'HL7 FHIR'],
    description: 'Pulse Health is looking for an ML Engineer to build the clinical intelligence models that power our point-of-care decision support. You will work with clinical data scientists and physicians to train, evaluate, and deploy models that improve patient outcomes.',
    requirements: [
      '3+ years of ML engineering experience',
      'Strong Python and PyTorch skills',
      'Experience with healthcare data formats (HL7 FHIR, OMOP)',
      'MLOps experience (experiment tracking, model deployment)',
      'Ability to work closely with non-technical clinical stakeholders',
    ],
    responsibilities: [
      'Train and evaluate clinical NLP and prediction models',
      'Build and maintain our ML training and inference infrastructure',
      'Collaborate with clinical data scientists on feature engineering',
      'Integrate models into our production API',
      'Ensure model safety, fairness, and regulatory compliance',
    ],
    postedAt: '2024-05-25',
    stage: 'series-a',
    industry: 'HealthTech',
    matchPercentage: 80,
  },
  {
    id: 'j8',
    title: 'Cloud Cost Engineer',
    companyId: 'c6',
    companyName: 'Stratos',
    location: 'Seattle, WA',
    locationType: 'remote',
    type: 'full-time',
    salaryMin: 140000,
    salaryMax: 185000,
    salaryCurrency: 'USD',
    techStack: ['Go', 'Python', 'AWS', 'GCP', 'BigQuery', 'Terraform'],
    description: 'Stratos is an early-stage startup building cloud cost intelligence. We need a Cloud Cost Engineer who understands the deep internals of AWS, GCP, and Azure billing, and can help us build the most accurate cost attribution engine in the industry.',
    requirements: [
      '3+ years of cloud infrastructure experience',
      'Deep familiarity with AWS Cost Explorer, GCP Billing, Azure Cost Management',
      'Experience with Go or Python',
      'Strong data engineering skills (SQL, BigQuery, dbt)',
      'Understanding of cloud pricing models (reserved instances, spot, committed use)',
    ],
    responsibilities: [
      'Build our multi-cloud cost data ingestion and normalization pipeline',
      'Design and implement cost attribution algorithms',
      'Create actionable cost optimization recommendations',
      'Work with customers to understand their cloud spending patterns',
      'Help define our product roadmap based on customer feedback',
    ],
    postedAt: '2024-06-07',
    batch: 'YC S24',
    stage: 'pre-seed',
    industry: 'Cloud Infrastructure',
    matchPercentage: 68,
  },
  {
    id: 'j9',
    title: 'Senior Go Engineer',
    companyId: 'c7',
    companyName: 'Sylva',
    location: 'Remote',
    locationType: 'remote',
    type: 'full-time',
    salaryMin: 160000,
    salaryMax: 215000,
    salaryCurrency: 'USD',
    techStack: ['Go', 'ClickHouse', 'OpenTelemetry', 'gRPC', 'Kubernetes'],
    description: 'Sylva is building open-source observability tooling that rivals the best commercial solutions. We need a Senior Go Engineer who is passionate about performance, reliability, and open-source software to help build the core of our platform.',
    requirements: [
      '5+ years of Go experience',
      'Experience with observability systems (Prometheus, Jaeger, OpenTelemetry)',
      'Experience with ClickHouse or similar column stores',
      'Strong understanding of distributed systems concepts',
      'Open-source contributions are a huge plus',
    ],
    responsibilities: [
      'Build core components of our log and trace ingestion pipeline',
      'Design and optimize our ClickHouse query layer',
      'Contribute to our OpenTelemetry integrations',
      'Maintain and improve our Kubernetes operator',
      'Engage with the open-source community',
    ],
    postedAt: '2024-05-20',
    stage: 'seed',
    industry: 'Developer Tools',
    matchPercentage: 87,
  },
  {
    id: 'j10',
    title: 'AI Product Engineer',
    companyId: 'c8',
    companyName: 'Forge Labs',
    location: 'San Francisco, CA',
    locationType: 'hybrid',
    type: 'full-time',
    salaryMin: 175000,
    salaryMax: 240000,
    salaryCurrency: 'USD',
    techStack: ['Python', 'TypeScript', 'React', 'LLMs', 'PostgreSQL'],
    description: 'Forge Labs is looking for an AI Product Engineer who sits at the intersection of machine learning and product development. You will build the AI-powered features that make our code review product feel magical — context-aware, precise, and genuinely useful.',
    requirements: [
      '4+ years of engineering experience',
      'Experience building LLM-powered products (prompt engineering, RAG, fine-tuning)',
      'Strong Python and TypeScript skills',
      'Product sensibility — you care about the end user experience',
      'Experience with code analysis or developer tools is a plus',
    ],
    responsibilities: [
      'Design and build AI-powered code review features',
      'Work on our RAG pipeline for codebase context',
      'Collaborate with product to define AI feature strategy',
      'Evaluate and improve model outputs for quality and accuracy',
      'Build evals and monitoring for AI system reliability',
    ],
    postedAt: '2024-06-06',
    batch: 'YC W22',
    stage: 'series-a',
    industry: 'Developer Tools',
    matchPercentage: 82,
  },
  {
    id: 'j11',
    title: 'Engineering Manager',
    companyId: 'c8',
    companyName: 'Forge Labs',
    location: 'San Francisco, CA',
    locationType: 'hybrid',
    type: 'full-time',
    salaryMin: 200000,
    salaryMax: 270000,
    salaryCurrency: 'USD',
    techStack: ['Python', 'TypeScript', 'React'],
    description: 'We are looking for an experienced Engineering Manager to lead our 8-person product engineering team. You will be responsible for delivery, technical quality, and the growth of your team members. You should still be technically hands-on.',
    requirements: [
      '2+ years of engineering management experience',
      '6+ years of software engineering experience',
      'Track record of shipping high-quality software on time',
      'Experience growing and mentoring engineers',
      'Strong communication and stakeholder management skills',
    ],
    responsibilities: [
      'Lead, mentor, and grow a team of 8 full-stack engineers',
      'Partner with product and design on roadmap planning',
      'Drive engineering excellence through process and culture',
      'Conduct regular 1:1s and performance reviews',
      'Recruit top engineering talent',
    ],
    postedAt: '2024-06-01',
    batch: 'YC W22',
    stage: 'series-a',
    industry: 'Developer Tools',
  },
  {
    id: 'j12',
    title: 'Backend Intern (Summer 2024)',
    companyId: 'c6',
    companyName: 'Stratos',
    location: 'Seattle, WA',
    locationType: 'hybrid',
    type: 'internship',
    salaryMin: 7000,
    salaryMax: 9000,
    salaryCurrency: 'USD',
    techStack: ['Go', 'Python', 'SQL'],
    description: 'Join Stratos as a summer intern and work on real problems in cloud cost optimization. You will be embedded on the core engineering team and ship features that our customers use.',
    requirements: [
      'Currently enrolled in a CS or related degree program',
      'Basic proficiency in Python or Go',
      'Strong fundamentals in data structures and algorithms',
      'Curiosity about cloud infrastructure',
    ],
    responsibilities: [
      'Build features for our cost data pipeline',
      'Write unit and integration tests',
      'Participate in code reviews and team standups',
      'Present your work at the end of the internship',
    ],
    postedAt: '2024-06-08',
    batch: 'YC S24',
    stage: 'pre-seed',
    industry: 'Cloud Infrastructure',
  },
];
